# Generated by Django 3.2.7 on 2022-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagearea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
