# Generated by Django 3.2.7 on 2022-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagearea', '0002_conversation_date_last_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='has_attachments',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immobilie_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('messages', models.ManyToManyField(to='messagearea.Message')),
            ],
        ),
    ]
